### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by srsross** [FrostyX/tracer#131]
On Fedora 30...

--- begin ---
$ rpm -qa \*tracer\*
tracer-common-0.7.1-4.fc30.noarch
python3-dnf-plugin-tracer-4.0.7-2.fc30.noarch
python3-tracer-0.7.1-4.fc30.noarch
$ sudo dnf update
⋮
  Verifying        : kernel-devel-5.1.12-300.fc30.x86_64                                                                                                  1142/1143 
  Verifying        : kernel-modules-5.1.12-300.fc30.x86_64                                                                                                1143/1143 
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 23, in with_helpers_content
    if application.helper_contains_formating and not application.helper_contains_name:
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 225, in helper_contains_formating
    return bool(re.search("\{.*\}", self.helper))
  File "/usr/lib64/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

Upgraded:
  flash-plugin-32.0.0.293-release.x86_64                                             gimp-2:2.10.14-1.module_f30+6995+c35e2138.x86_64                               
  gimp-libs-2:2.10.14-1.module_f30+6995+c35e2138.x86_64                              ImageMagick-1:6.9.10.67-1.fc30.x86_64                                          
⋮

--- end ---

**Comment by 9strands** [comment]
I just hit the same error in Fedora 31.  Error and packages being upgraded are here:

`Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 23, in with_helpers_content
    if application.helper_contains_formating and not application.helper_contains_name:
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 225, in helper_contains_formating
    return bool(re.search("\{.*\}", self.helper))
  File "/usr/lib64/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

Upgraded:
  e2fsprogs-1.45.5-1.fc31.x86_64     e2fsprogs-libs-1.45.5-1.fc31.x86_64    glibc-2.30-10.fc31.x86_64                      glibc-all-langpacks-2.30-10.fc31.x86_64  glibc-common-2.30-10.fc31.x86_64      glibc-devel-2.30-10.fc31.x86_64 
  glibc-headers-2.30-10.fc31.x86_64  glibc-langpack-en-2.30-10.fc31.x86_64  libcom_err-1.45.5-1.fc31.x86_64                librados2-2:14.2.6-2.fc31.x86_64         librbd1-2:14.2.6-2.fc31.x86_64        libss-1.45.5-1.fc31.x86_64      
  nss-3.49.0-1.fc31.x86_64           nss-softokn-3.49.0-1.fc31.x86_64       nss-softokn-freebl-3.49.0-1.fc31.x86_64        nss-sysinit-3.49.0-1.fc31.x86_64         nss-tools-3.49.0-1.fc31.x86_64        nss-util-3.49.0-1.fc31.x86_64   
  pptp-1.10.0-8.fc31.x86_64          selinux-policy-3.14.4-44.fc31.noarch   selinux-policy-targeted-3.14.4-44.fc31.noarch  socat-1.7.3.4-1.fc31.x86_64              switcheroo-control-2.1-1.fc31.x86_64  xen-libs-4.12.2-2.fc31.x86_64   
  xen-licenses-4.12.2-2.fc31.x86_64  zchunk-libs-1.1.5-1.fc31.x86_64       

Installed:
  kernel-5.4.12-200.fc31.x86_64           kernel-core-5.4.12-200.fc31.x86_64           kernel-devel-5.4.12-200.fc31.x86_64           kernel-modules-5.4.12-200.fc31.x86_64           kernel-modules-extra-5.4.12-200.fc31.x86_64          

Removed:
  kernel-5.4.7-200.fc31.x86_64            kernel-core-5.4.7-200.fc31.x86_64            kernel-devel-5.4.7-200.fc31.x86_64            kernel-modules-5.4.7-200.fc31.x86_64            kernel-modules-extra-5.4.7-200.fc31.x86_64  `
