### ISSUE TITLE
2020-03-13: Fedora 32: TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by sanjayankur31** [FrostyX/tracer#133]
```
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.8/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.8/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.8/site-packages/tracer/views/default.py", line 23, in with_helpers_content
    if application.helper_contains_formating and not application.helper_contains_name:
  File "/usr/lib/python3.8/site-packages/tracer/resources/applications.py", line 225, in helper_contains_formating
    return bool(re.search("\{.*\}", self.helper))
  File "/usr/lib64/python3.8/re.py", line 199, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

```

Various package versions:

```
$ rpm -qa \*dnf\* \*tracer\*
libdnf-0.45.0-2.fc32.x86_64
python3-dnf-plugins-core-4.0.14-1.fc32.noarch
python3-dnf-4.2.19-1.fc32.noarch
dnf-plugins-core-4.0.14-1.fc32.noarch
python3-dnf-plugin-versionlock-4.0.14-1.fc32.noarch
dnf-utils-4.0.14-1.fc32.noarch
traceroute-2.1.0-10.fc32.x86_64
python3-dnf-plugins-extras-common-4.0.9-5.fc32.noarch
python3-libdnf-0.45.0-2.fc32.x86_64
tracer-common-0.7.1-8.fc32.noarch
python3-dnf-plugin-system-upgrade-4.0.9-5.fc32.noarch
python3-dnf-plugin-tracer-4.0.9-5.fc32.noarch
dnf-data-4.2.19-1.fc32.noarch
python3-tracer-0.7.1-8.fc32.noarch
dnf-4.2.19-1.fc32.noarch
 ```

**Comment by pjoc** [comment]
Me too:
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer.render()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
    return view.render()
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
    {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
  File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 23, in with_helpers_content
    if application.helper_contains_formating and not application.helper_contains_name:
  File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 225, in helper_contains_formating
    return bool(re.search("\{.*\}", self.helper))
  File "/usr/lib64/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

$ rpm -qa \*dnf\* \*tracer\*
python3-dnf-4.2.18-1.fc31.noarch
dnf-plugins-core-4.0.13-1.fc31.noarch
python3-tracer-0.7.1-5.fc31.noarch
libdnf-0.43.1-5.fc31.x86_64
dnf-data-4.2.18-1.fc31.noarch
python3-dnf-plugins-extras-common-4.0.8-4.fc31.noarch
python3-dnf-plugins-core-4.0.13-1.fc31.noarch
tracer-common-0.7.1-5.fc31.noarch
python3-dnf-plugin-tracer-4.0.8-4.fc31.noarch
traceroute-2.1.0-9.fc31.x86_64
python3-libdnf-0.43.1-5.fc31.x86_64
dnf-4.2.18-1.fc31.noarch

**Comment by gvansickle** [comment]
Just got the same thing on Fedora 31:

> Tracer:
>  Call to Tracer API ended unexpectedly:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 67, in transaction
>     tracer.render()
>   File "/usr/lib/python3.7/site-packages/dnf-plugins/tracer.py", line 92, in render
>     return view.render()
>   File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 59, in render
>     {"title": "  * " + _("Some applications using:"), "content": with_helpers_content()},
>   File "/usr/lib/python3.7/site-packages/tracer/views/default.py", line 23, in with_helpers_content
>     if application.helper_contains_formating and not application.helper_contains_name:
>   File "/usr/lib/python3.7/site-packages/tracer/resources/applications.py", line 225, in helper_contains_formating
>     return bool(re.search("\{.*\}", self.helper))
>   File "/usr/lib64/python3.7/re.py", line 183, in search
>     return _compile(pattern, flags).search(string)
> TypeError: expected string or bytes-like object
> 
> Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
> We apologize for any inconvenience
> 

Is this thing on?

**Comment by FrostyX** [comment]
Hello guys, I was trying to reproduce the issue but I wasn't successful.
Does it happen to you every time you run tracer?

If you are able to create a deterministic reproducer, I will promptly fix it.

**Comment by pjoc** [comment]
> Hello guys, I was trying to reproduce the issue but I wasn't successful.
> Does it happen to you every time you run tracer?
> 
> If you are able to create a deterministic reproducer, I will promptly fix it.

It doesn't happen every time. In fact since I upgraded to F32 I haven't seen it. I'll report if it happens again.

**Comment by FrostyX** [comment]
@pjoc I actually skipped F31 and went F30 -> F32, so I just haven't encountered the issue.
