### ISSUE TITLE
Please provide package for EPEL / Enterprise Linux 8

### ISSUE THREAD

**Issue by MalteP** [FrostyX/tracer#139]
I was able to install tracer via PIP, but it would be nice to have a EPEL package for CentOS 8, too.

**Comment by sean797** [comment]
If its of help in the short term, The Foreman community have alreay done this in their own repo https://yum.theforeman.org/client/2.0/el8/x86_64/

**Comment by FrostyX** [comment]
There is currently an EPEL8 package in testing
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-c8fdb301c5

do you want to try it?

**Comment by MalteP** [comment]
Thank you very much!

I've installed the package from EPEL testing. When running tracer, the following warnings are shown:

> /usr/lib/python3.6/site-packages/tracer/packageManagers/rpm.py:201: UnicodeWarning: decode() called on unicode string, see https://bugzilla.redhat.com/show_bug.cgi?id=1693751
>   package.description = hdr[rpm.RPMTAG_SUMMARY].decode()
> /usr/lib/python3.6/site-packages/tracer/packageManagers/rpm.py:202: UnicodeWarning: decode() called on unicode string, see https://bugzilla.redhat.com/show_bug.cgi?id=1693751
>   package.category = hdr[rpm.RPMTAG_GROUP].decode()
> /usr/lib/python3.6/site-packages/tracer/packageManagers/rpm.py:208: UnicodeWarning: decode() called on unicode string, see https://bugzilla.redhat.com/show_bug.cgi?id=1693751
>   package.version = hdr[rpm.RPMTAG_VERSION].decode()
> /usr/lib/python3.6/site-packages/tracer/packageManagers/rpm.py:209: UnicodeWarning: decode() called on unicode string, see https://bugzilla.redhat.com/show_bug.cgi?id=1693751
>   package.release = hdr[rpm.RPMTAG_RELEASE].decode()

**Comment by FrostyX** [comment]
Ah, actually we have currently opened PRs for that issues, so I will make a new release with them soon.

**Comment by FrostyX** [comment]
@MalteP, do you still getting the errors? I think they should be fixed now.
Also, Tracer is now available in RHEL 8.4 (yaaay :partying_face:) but I accidentally removed it from EPEL 8 repositories too soon, so there is no official repo for 8.3 and lower. There is a Copr repository though.
https://copr.fedorainfracloud.org/coprs/frostyx/tracer/

Does this work for you?
