### ISSUE TITLE
Please add section on tracer exit codes to tracer man page

### ISSUE THREAD

**Issue by hartwork** [FrostyX/tracer#154]
Hi!

I found the exit code documentation at https://github.com/FrostyX/tracer/blob/a6c14536f37f02ca68e10dbeeac42208cb55f089/doc/source/api.rst#exit-codes eventually but it would be nice to have documentation right in `man tracer` at the user's fingertips. What do you think?

Best, Sebastian

**Comment by FrostyX** [comment]
Thank you for the feedback @hartwork,
please see PR #155.
