### ISSUE TITLE
Enhacement: Do not show sudo among result

### ISSUE THREAD

**Issue by skobyda** [FrostyX/tracer#162]
When sudo package is update while it was running some program, 'sudo' is listed among "You should restart... These applications manually" .

But that's not really helpful, since 'sudo' only started the program which is now running and 'sudo' itself is not really doing anything anymore. It's also hard to find what program needs to be restarted.

So instead of 'sudo', perhaps a program which 'sudo' started should be shown instead as to be restarted manually? Or perhaps do not show 'sudo' at all?

**Comment by martinpitt** [comment]
IMHO sudo should just be filtered out. sudo forks the program that runs as root, so it will be considered and shown separately by tracer (if it uses any updated libraries etc.)
