### ISSUE TITLE
Missing tracer package in EPEL / Enterprise Linux 8 

### ISSUE THREAD

**Issue by Koleon** [FrostyX/tracer#167]
Hello guys,
it seems like the tracer package has been removed from EPEL / Enterprise Linux 8 repository. Do you know why that happened?
Is there any chance it will be there again in upcoming days? Or is it better to install it via [this repo](https://copr.fedorainfracloud.org/coprs/frostyx/tracer/repo/epel-8/frostyx-tracer-epel-8.repo)?

Thank you

**Comment by FrostyX** [comment]
Hello @Koleon,
the tracer package is now available in RHEL 8.4, so I dropped it from EPEL8.

Currently, it is available in CentosStream repo http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/
does it help?

**Comment by Koleon** [comment]
Hi @FrostyX ,
thank you for you reply. Needless to say the RHEL 8.4 is in Beta right now, so how could I install the package please? Is the only way to install it via beta repository or wait until the RHEL8.4 is officially released? Because even after I run `dnf --releasever=8.4 update`, I cannot find the `tracer` package at the moment.

**Comment by FrostyX** [comment]
True, my apologies, I was too hasty with the retirement. It is my first RHEL package and got the impression that we are already at the point when I should retire it from EPEL. I should have waited.

Would it be a problem for you to temporarily use the Copr repo you linked? I build the package there just before submitting it to Fedora, so it doesn't contain any bleeding edge things.

**Comment by Koleon** [comment]
Oh I see, no worries. Well I will have to come up with a workaround. Didn't expect a package could suddenly disappear from EPEL repo this way. :sweat_smile: 

Anyway I'm glad you made it to push `tracer` to official repo. I'm happy to use it.

**Comment by Koleon** [comment]
Maybe one more question, @FrostyX . Do you have any idea when could be the RHEL 8.4 released? Thank you
