### ISSUE TITLE
The imp module is deprecated in favor of importlib.

### ISSUE THREAD

**Issue by jelly** [FrostyX/tracer#178]
```
tracer/hooks.py:20
  /home/jelle/projects/tracer/tracer/hooks.py:20: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
```

Is Python < 3.1 still required? As that's the version which introduced `importlib` otherwise some fallback code is required?

**Comment by FrostyX** [comment]
Hello @jelly,
I still build Tracer for EPEL7 which has 2.7.5 but it seems like `importlib` is available there. Let me try to fix the code.

**Comment by FrostyX** [comment]
Modified in PR #180,
what do you think @jelly?

**Comment by jelly** [comment]
Looks good to me!
