### ISSUE TITLE
It does nothing on Oracle Linux 7 and 8

### ISSUE THREAD

**Issue by toptnc** [FrostyX/tracer#186]
I'm trying to use tracer with Oracle Linux (in conjunction with katello-host-tools-tracer) but I have found that tracer always return 0 even if I install a new kernel. The result is always the same. No messages, no errors, nothing.

I have tried with version 0.7.3, shipped with katello-host-tools-tracer, 0.7.5, from OL8 appstream repo, and 0.7.8 from EPEL repo, with no success.

The behavior is always the same

```
# tracer
# echo $?
0
# tracer -a
# echo $?
0

```

**Comment by FrostyX** [comment]
Thank you for the report @toptnc,
this will probably get fixed by PR #184.

**Comment by xsuchy** [comment]
@toptnc can this be closed now?

**Comment by toptnc** [comment]
Yes. Thanks
