### ISSUE TITLE
Tracer confused by deleted file

### ISSUE THREAD

**Issue by xsuchy** [FrostyX/tracer#19]
Tracer suggest me to manually restart plugin-container (which is flash-plugin to Firefox), which according the rule should transition to Firefox.

When I manualy started ```tracer -iat 1413404315.07``` and select plugin-container option. I got:
```
--> 39
error: file /usr/lib64/firefox/plugin-container.#prelink#.N3n7Rk: No such file or directory
* plugin-container
    Package:     plugin-container is not provided by any package
    State:       plugin-container has been started by mirek 11 hours ago. PID - 5237
```
and
```
$ lsof | grep lugin-container
plugin-co  5237          mirek  txt       REG                8,1      96480    2108839 /usr/lib64/firefox/plugin-container.#prelink#.N3n7Rk (deleted)
Chrome_Ch  5237  5238    mirek  txt       REG                8,1      96480    2108839 /usr/lib64/firefox/plugin-container.#prelink#.N3n7Rk (deleted)
plugin-co  5237  5242    mirek  txt       REG                8,1      96480    2108839 /usr/lib64/firefox/plugin-container.#prelink#.N3n7Rk (deleted)
plugin-co  5237  5243    mirek  txt       REG                8,1      96480    2108839 /usr/lib64/firefox/plugin-container.#prelink#.N3n7Rk (deleted)
plugin-co  5237  5244    mirek  txt       REG                8,1      96480    2108839 /usr/lib64/firefox/plugin-container.#prelink#.N3n7Rk (deleted)
plugin-co  5237  5245    mirek  txt       REG                8,1      96480    2108839 /usr/lib64/firefox/plugin-container.#prelink#.N3n7Rk (deleted)
plugin-co  5237  5247    mirek  txt       REG                8,1      96480    2108839 /usr/lib64/firefox/plugin-container.#prelink#.N3n7Rk (deleted)
plugin-co  5237  6728    mirek  txt       REG                8,1      96480    2108839 /usr/lib64/firefox/plugin-container.#prelink#.N3n7Rk (deleted)
```
Where PID 5237 is:
```
$ ps axf |grep 5237
 5237 ?        Sl     8:17  |   \_ /usr/lib64/firefox/plugin-container /usr/lib64/flash-plugin/libflashplayer.so -greomni /usr/lib64/firefox/omni.ja -appomni /usr/lib64/firefox/browser/omni.ja -appdir /usr/lib64/firefox/browser 4801 true plugin
```
So you should identify that it belong to firefox either from that pid, or by removing ```.#prelink#.<randomstuff>``` from file name before querying package manager or quering roles rules.

**Comment by FrostyX** [comment]
Hi Miroslav,
thank you for reporting this.

I think we are talking two unrelated issues.

##### First:
> So you should identify that it belong to firefox either from that pid, or by removing `.#prelink#.<randomstuff>` from file name before querying package manager or quering roles rules.

Sure, this was a bug. I had no luck with reproducing this, but test passed, so I think it should be fixed now. Please see 6ad7aa427b123fc1783941d8255a20e79620c32a.

##### Second:
> Tracer suggest me to manually restart plugin-container (which is flash-plugin to Firefox), which according the rule should transition to Firefox.

It is very easy to forget, but for every found process, tracer goes up to his parent, see **its** rules and then reacts:
1. Rule is not found => previously found child is printed
2. Rule with `action="call-parent"` or none `action` => tracer goes up to next parent and the whole process recursively repeats itself.
3. Rule with `action="print"` => return the process which rule belongs to

This means, when you want to say tracer, that `plugin-container` is part of the `firefox` so suggest me firefox, then you actually have to add rule for `firefox` saying that *firefox is the whole application and should be printed*

    <rule name="firefox" action="print" />

And for processes which are parent to found processes, but **not** the *whole application* what should be printed, you should add:

    <rule name="chrome-sandbox" action="call-parent" />


PS: Action `print` is relatively new and not used on much applications yet. I am not sure if I woudn't like `action="return"` better. Also I consider about changing default action to it.

**Comment by FrostyX** [comment]
Adding rule for firefox in fdf281ad8f8ac0f3df4d5bc25ebdda29524ca34a. I will change its `action` later (with all other applications at once).
