### ISSUE TITLE
RFE: Write /var/run/reboot-required if reboot is needed

### ISSUE THREAD

**Issue by major** [FrostyX/tracer#195]
I'm one of the maintainers of cloud-init in Fedora and [BZ 1275409](https://bugzilla.redhat.com/show_bug.cgi?id=1275409) is an RFE for cloud-init to support automatic reboots of Fedora instances when packages were updated that needed a reboot.

Debian/Ubuntu systems automatically write data to `/var/run/reboot-required` when `apt` runs and detects that something critical (openssl, for example) has changed and a reboot is needed to put the changes into effect. After a package update, `cloud-init` looks for the `/var/run/reboot-required` file and reboots the instance (if the user asked for automatic reboots in their instance metadata when they launched the instance).

If tracer could use this same pattern and write data to that file when updates occur, then cloud-init could use that information to know when a reboot is needed.

**Comment by FrostyX** [comment]
Hello @major,
thank you for the RFE, I appreciate your cloud-init automatic reboots initiative.

I implemented the proposed feature in PR #196. Do you want to try it?

**Comment by major** [comment]
@FrostyX thanks -- commented in the PR
