### ISSUE TITLE
stop using subprocess.Popen for RPM calls

### ISSUE THREAD

**Issue by ignatenkobrain** [FrostyX/tracer#30]
you can find some examples how to use RPM from python in:
* https://github.com/xsuchy/rpmconf/commit/c3649e7b4369fb216141b36570bb58e819c57b7a
* https://github.com/xsuchy/rpmconf/commit/d1ccb39c0a44c8b041585d0251514ff70b4df01b

For example, after one of this commits speeded up `rpmconf` from 2 minutes to 10 seconds (https://github.com/xsuchy/rpmconf/pull/14#issuecomment-63476843)

**Comment by FrostyX** [comment]
Fixed by #31
