### ISSUE TITLE
Tracer crashes with parsing error

### ISSUE THREAD

**Issue by ktlikes** [FrostyX/tracer#39]
/usr/lib/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")

  markup_type=markup_type))

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

**Comment by FrostyX** [comment]
Hello @ktlikes,
thank you for the feedback.

This issue has already been reported by few users on RedHat bugzilla and was fixed in 7f45aed.

I am closing this issue here, please watch the progress on: 
<https://bugzilla.redhat.com/show_bug.cgi?id=1240115>
