### ISSUE TITLE
should report that reboot is necessary for new kernels

### ISSUE THREAD

**Issue by peccuflo** [FrostyX/tracer#45]
Tracer does not report that a reboot is necessary after updating only kernel packages. This is presumably because kernel packages are marked installonly -- perhaps a special condition should be triggered for kernel packages to indicate that a reboot is needed, or perhaps users should be warned if any installonly package is installed (I don't know if any others exist besides for kernel).

**Comment by FrostyX** [comment]
Thank you for the feedback.
This is definitely a bug. Very simple reproducer:

    sudo dnf update kernel
    sudo tracer -e
    # There should be some note about kernel

**Comment by gsauthof** [comment]
I wrote [this simple shell script](https://github.com/gsauthof/utility/blob/master/latest-kernel-running.sh) to check the kernel version. Can be used as work-around until this issue is fixed.

**Comment by sean797** [comment]
Created https://github.com/FrostyX/tracer/pull/83.
If someone can validate the approach that would be great, I think it will work across all distros ?

**Comment by sean797** [comment]
Closing fixed in #83
