### ISSUE TITLE
Don't force root if not required

### ISSUE THREAD

**Issue by rhopfer** [FrostyX/tracer#49]
It is a very bad practice to force to be root. Root should used as less as possible. 
Better print a notice.

**Comment by FrostyX** [comment]
I absolutely agree with this, but as regular user you don't have a permissions to open package manager's database.

Last time that I've checked it, DNF didn't provided API for all data which tracer needs. But I will try to look on it again, and make some requests.

It would be nice to have it working for regular users.

**Comment by FrostyX** [comment]
This is probably all I can do now.

It is not forced to be root now, but tracer still hits the point when it needs to open DNF database and fails if has no read permissions for it.

So for instance this will now work for every user

    [frostyx]$ tracer --show-resource=system
    Python:             2.7.10
    Distribution:       fedora
    Package Manager:    Dnf, Yum
    ...

but unfortunately all meaningful commands will still fail

    [frostyx]$ tracer
    You can't open package database due to insufficient permissions
    You will probably need to run tracer as root

**Comment by rhopfer** [comment]
Thank you! This is ok for me. I tried it after a world update and it shows me the list of programs if I am in the portage group.

**Comment by FrostyX** [comment]
> if I am in the portage group

Aha, that's great. I will try it and make some note about it in the documentation. Thank you! :+1:

> This is ok for me

Ok, so I am closing this issue and I will release a new tracer version.
