### ISSUE TITLE
-r / --root option not working

### ISSUE THREAD

**Issue by wheslaeblue** [FrostyX/tracer#51]
[root@localhost ~]# tracer -r
[root@localhost ~]# tracer --root
[root@localhost ~]# tracer -u root
You should restart:
  * Some applications using:
      sudo service NetworkManager restart
      sudo service abrtd restart
      sudo service accounts-daemon restart
      sudo service lightdm restart
      sudo service systemd-journald restart
      sudo service systemd-logind restart
      sudo service systemd-udevd restart

  * These applications manually:
      Xorg
      cupsd
      lvmetad
      rsyslogd
      sd-pam
      systemd

Additionally to those process above, there are:
  - 3 processes requiring reboot

**Comment by FrostyX** [comment]
Hello @wheslaeblue, thank you for the feedback. I can confirm the issue.
