### ISSUE TITLE
Option to restart applications if method known

### ISSUE THREAD

**Issue by tsujamin** [FrostyX/tracer#52]
For machines that run automatic security updates, it would be useful if tracer were configurable to execute service restarts for daemons it knows about. This could be enabled by a command line switch, or a configuration file for the dnf-plugin (with white listing of particular packages).

Not sure if this is a function you see tracer fulfilling, but I might hack on it a bit if I find some time.

**Comment by FrostyX** [comment]
I personally haven't needed this, but I agree that it can be nice in some scenarios. Feel free to send PR if you want to code it by yourself :-). Or I will do it, but it can take some while.

**Comment by tsujamin** [comment]
I've started on an implementation (https://github.com/tsujamin/tracer) which adds a new Controller/View for restarting services and the commandline flags "--restart-daemons" and "--restart-services"

I've tried to mock up some unit tests for the controller, which appear to pass, but I haven't really been able to test it in practice as I don't have any daemons that need restarting ;) How should I go about testing this properly?

I'll probably look into integrating this with the dnf-plugin, but it appears that's in a separate project at the moment. If it were to go that far, being able to enable/disable the functionality and blacklist certain packages from automatic restarts would be something I'd look to implement (probably with ConfigParser or something similar), but I figured I'd run this past you before going any further :)

**Comment by gsauthof** [comment]
FWIW, while waiting on this feature I implemented an alternative stale-process-checker that supports automatic restarts via `--restart`: https://github.com/gsauthof/utility/#oldprocs

**Comment by tsujamin** [comment]
Ah interesting ty, I’ve moved on from the role I was using this in so all good

happy new year!

On 1 Jan 2022, at 12:30 am, Georg Sauthoff ***@***.***> wrote:

﻿

FWIW, while waiting on this feature I implemented an alternative stale-process-checker that supports automatic restarts via --restart: https://github.com/gsauthof/utility/#oldprocs

**Comment by FrostyX** [comment]
> I've started on an implementation
> (https://github.com/tsujamin/tracer) which adds a new
> Controller/View for restarting services and the commandline flags
> "--restart-daemons" and "--restart-services" 

Ah, I am sorry, I somehow missed the comment. I guess it's not
relevant anymore.

> FWIW, while waiting on this feature I implemented an alternative
> stale-process-checker that supports automatic restarts via --restart:
> https://github.com/gsauthof/utility/#oldprocs 

Perhaps I should add a section with known alternatives to the README
section and mention your tool?

> @tsujamin tsujamin closed this 4 days ago

Also, if you don't mind, I would keep this issue open. It's a valid
RFE.

**Comment by gsauthof** [comment]
> Perhaps I should add a section with known alternatives to the README
> section and mention your tool?

Sure, adding a section that puts a project into perspective like that usually is a good idea.

**Comment by FrostyX** [comment]
@gsauthof I added a Similar software section to the README in  b390877, feel free to edit it or list other alternatives.
