### ISSUE TITLE
Build package for F24

### ISSUE THREAD

**Issue by xasx** [FrostyX/tracer#58]
Since Fedora 24 is available for quite some time now, how about building the respective package in Bodhi?

cf. https://bodhi.fedoraproject.org/updates/FEDORA-2016-21b911354e

Thanks in advance.

**Comment by FrostyX** [comment]
Hello @xasx, thank you for noticing.
I've added F24 in 6fc6d1b and I will release new version and build packages when this packaging issue  [RhBug: 1333169](https://bugzilla.redhat.com/show_bug.cgi?id=1333169) is finished.

**Comment by sean797** [comment]
Closing, it seems we have release a F24 pkg now 🥂
