### ISSUE TITLE
[RFE] Use process cgroup to get the service 

### ISSUE THREAD

**Issue by sean797** [FrostyX/tracer#67]
Use the process cgroup to check what service it belongs to. This could be more reliable than our current method.

**Comment by tjanez** [comment]
Is this the same as using [systemd D-Bus API](https://www.freedesktop.org/wiki/Software/systemd/dbus/)'s `GetUnitByPID` method?

I've tested this and it works nicely. For example, to get the service name for a Postfix's subprocess `tlsmgr` with PID `12457`, one can use the following `gdbus` command.

```bash
$ systemctl status postfix.service 
● postfix.service - Postfix Mail Transport Agent
   Loaded: loaded (/usr/lib/systemd/system/postfix.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-04-18 14:21:42 CEST; 5 days ago
 Main PID: 1838 (master)
   CGroup: /system.slice/postfix.service
           ├─ 1838 /usr/libexec/postfix/master -w
           ├─ 1871 qmgr -l -t unix -u
           ├─12457 tlsmgr -l -t unix -u
           └─57532 pickup -l -t unix -u

[ ... log removed ... ]
$ gdbus call --system --dest org.freedesktop.systemd1   --object-path /org/freedesktop/systemd1   --method org.freedesktop.systemd1.Manager.GetUnitByPID 12457
(objectpath '/org/freedesktop/systemd1/unit/postfix_2eservice',)
```

This would also fix issues like #74 easily.

**Comment by sean797** [comment]
@tjanez They are different things. I think using `GetUnitByPID` would actually be better though, cgroups are not required to have a name related to the services or group of process (although they often do). And there is no mapping between cgroup -> Unit AFAIK

```
$ gdbus call --system --dest org.freedesktop.systemd1   --object-path /org/freedesktop/systemd1   --method org.freedesktop.systemd1.Manager.GetUnitByPID 6037
(objectpath '/org/freedesktop/systemd1/unit/postfix_2eservice',)
$
$ gdbus introspect --system --dest org.freedesktop.systemd1   --object-path /org/freedesktop/systemd1/unit/postfix_2eservice | grep ControlGroup
      readonly s ControlGroup = '/system.slice/postfix.service';
$
$ cat /sys/fs/cgroup/systemd/system.slice/postfix.service/cgroup.procs 
6035
6036
6037
$
$ cat /proc/6037/cgroup 
11:memory:/system.slice
10:cpuset:/
9:devices:/system.slice/postfix.service
8:perf_event:/
7:hugetlb:/
6:pids:/system.slice/postfix.service
5:blkio:/system.slice
4:net_cls,net_prio:/
3:freezer:/
2:cpu,cpuacct:/system.slice
1:name=systemd:/system.slice/postfix.service

````

**Comment by tjanez** [comment]
> @tjanez They are different things. 

I see, thanks for the explanation.

> I think using GetUnitByPID would actually be better though, cgroups are not required to have a name related to the services or group of process (although they often do). And there is no mapping between cgroup -> Unit AFAIK

Agreed. Should I file a new RFE for using systemd's `GetUnitByPID` or should we edit this one?

**Comment by sean797** [comment]
File a new one please 👍

**Comment by tjanez** [comment]
> File a new one please 👍

Done: #80.

**Comment by sean797** [comment]
Closing this one in favor of https://github.com/FrostyX/tracer/issues/80
