### ISSUE TITLE
Unknown or unsupported linux distribution: ol (v0.6.12)

### ISSUE THREAD

**Issue by malaiwah** [FrostyX/tracer#73]
This is on Oracle Linux 7.3 -- it is Redhat-based using Yum so I'm sure it can be supported.

[root@fplab-util-02 ~]# grep . /etc/*release
/etc/oracle-release:Oracle Linux Server release 7.3
/etc/os-release:NAME="Oracle Linux Server"
/etc/os-release:VERSION="7.3"
/etc/os-release:ID="ol"
/etc/os-release:VERSION_ID="7.3"
/etc/os-release:PRETTY_NAME="Oracle Linux Server 7.3"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:oracle:linux:7:3:server"
/etc/os-release:HOME_URL="https://linux.oracle.com/"
/etc/os-release:BUG_REPORT_URL="https://bugzilla.oracle.com/"
/etc/os-release:ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
/etc/os-release:ORACLE_BUGZILLA_PRODUCT_VERSION=7.3
/etc/os-release:ORACLE_SUPPORT_PRODUCT="Oracle Linux"
/etc/os-release:ORACLE_SUPPORT_PRODUCT_VERSION=7.3
/etc/redhat-release:Red Hat Enterprise Linux Server release 7.3 (Maipo)
/etc/system-release:Oracle Linux Server release 7.3
[root@fplab-util-02 ~]# /sbin/katello-tracer-upload
Traceback (most recent call last):
  File "/sbin/katello-tracer-upload", line 13, in <module>
    main()
  File "/sbin/katello-tracer-upload", line 10, in main
    tracer_upload.upload_tracer_profile()
  File "/usr/lib/yum-plugins/tracer_upload.py", line 56, in upload_tracer_profile
    data =  json.dumps({ "traces": get_apps(conduit) })
  File "/usr/lib/yum-plugins/tracer_upload.py", line 47, in get_apps
    for app in query_apps(conduit):
  File "/usr/lib/yum-plugins/tracer_upload.py", line 22, in query_apps
    query = Query()
  File "/usr/lib/python2.7/site-packages/tracer/query.py", line 44, in __init__
    self._tracer = tracer(System.package_manager(), Rules, Applications, dump_memory)
  File "/usr/lib/python2.7/site-packages/tracer/resources/tracer.py", line 65, in __init__
    raise UnsupportedDistribution(System.distribution())
tracer.resources.exceptions.UnsupportedDistribution: You are running unsupported linux distribution

Please visit https://github.com/FrostyX/tracer/issues
and create new issue called 'Unknown or unsupported linux distribution: ol (v0.6.12)' if there isn't such.

Don't you have an GitHub account? Please report this issue on frostyx@email.cz

**Comment by malaiwah** [comment]
In fact it seems it works just fine if I fake it in /etc/os-release.

[root@fplab-util-02 ~]# sed -i -e 's/ID="ol"/ID="rhel"/' /etc/os-release
[root@fplab-util-02 ~]# /sbin/katello-tracer-upload
[root@fplab-util-02 ~]#

**Comment by FrostyX** [comment]
Hi @malaiwah,
thank you for filing the issue.

I guess when you run

    python -c "from tracer.resources.system import System; print System.distribution();"

on your system, you will get `ol` right? I can add support for this. Is DNF installed on Oracle Linux by default or there is only YUM?

**Comment by FrostyX** [comment]
I will probably rewrite the hardcoded `Distro -> Package manager` mapping to something more dynamic, so we won't have to deal with situations like this in the future :-)

**Comment by malaiwah** [comment]
Yes it returns "ol". No DNF, only YUM.
