### ISSUE TITLE
tracer doesn't recognize postfix

### ISSUE THREAD

**Issue by gsauthof** [FrostyX/tracer#74]
Running current tracer on CentOS 7 after a openssl update yields the following output:

    # tracer -e
    You should restart:
    * Some applications using:
      systemctl restart NetworkManager
      systemctl restart cups
      systemctl restart firewalld
      systemctl restart libvirtd
      systemctl restart nginx
      systemctl restart sshd
      systemctl restart tuned

    * These applications manually:
      master
      qmgr
      tlsmgr

The last 3 processes are part of postfix, thus my expectation is that tracer would just print

    systemctl restart postfix

instead.

And indeed, after restarting all the mentioned services plus postfix another `tracer -e` reports nothing.

This is with the git head of tracer. Tracer from EPEL is currently at 0.6.12 and that version also misses cups.

**Comment by sean797** [comment]
Thanks for reporting this @gsauthof 👍 I've updated `applications.xml` for now. Leaving this open as we should probably find a better way for doing this, @FrostyX any ideas? (sssd,cups, maybe others have the same problem)

@gsauthof if you don't want to wait for the next release you should be able to copy https://github.com/FrostyX/tracer/blob/master/data/applications.xml to `/etc/tracer/applications.xml` or `~/.config/tracer/applications.xml` on your system.

**Comment by sean797** [comment]
Closing this one in favor of https://github.com/FrostyX/tracer/issues/80
