### ISSUE TITLE
polkitd not mentioned and doesn't really require reboot

### ISSUE THREAD

**Issue by gsauthof** [FrostyX/tracer#76]
Recently, a `tracer -e` yielded the following output on a CentOS 7 system (after a yum update):

    # tracer -e
    You should restart:
    There are:
      - 1 processes requiring reboot

There is arguably room for improvement:

- The `You should restart:` part could be left out, because it is empty
- the `1 processes` message could dynamically change singular/plural such that it is grammatically correct
- the most important information is missing: the name of the process that requires the reboot! 

Calling repeatedly `tracer -u user` for all active users shows that the above message is causes by `polkitd`:

    # tracer -u polkitd
    You should restart:
    There are:
      - 1 processes requiring reboot
    # systemctl restart polkit.service 
    PolicyKit daemon disconnected from the bus.
    We are no longer a registered authentication agent.
    PolicyKit daemon reconnected to bus.
    Attempting to re-register as an authentication agent.
    # tracer -u polkitd               
    # tracer -e
    # 

This also shows that a reboot isn't really necessary.

Expected behavior: tracer explicitly lists policykitd and the corresponding `systemctl restart` command; if tracer identifies a process as requiring a reboot then it also includes its name

**Comment by FrostyX** [comment]
Hello @gsauthof, thank you for the feedback

> The You should restart: part could be left out, because it is empty

Sounds reasonable

> the most important information is missing: the name of the process that requires the reboot!

This is a feature. Imagine that you have a lot of processes that requires reboot. You might not want to see them all the time. At least I don't. But you can use `-a` parameter if you want

    -a, --all             list even session and unrestartable applications

then all output sections prints process names (or helpers)

> the above message is causes by polkitd

It seems that I mistakenly put polkitd into processes, that requires reboot <https://github.com/FrostyX/tracer/blob/master/data/applications.xml#L131>. This line should be removed and polkit will be listed as a regular daemon.

**Comment by gsauthof** [comment]
Yes, `-a` looks good - I just tried `-v` and `-vv` which didn't help in the described case.

Ok, I tested `-a` on another CentOS 7 box and with it I get:

    # tracer -a -e
    You should restart:
      * These applications rebooting your computer:
          polkitd

I think that the grammar/wording can be improved, e.g.:
- These applications via rebooting your computer.

With the polkitd line removed from the static group (in `applications.xml`) I get:

    # tracer  -e                                           
    You should restart:
      * These applications manually:
          polkitd

When adding the polkitd line to the daemon group I get the expected behavior, though:

    # tracer  -e
    You should restart:
      * Some applications using:
          systemctl restart polkitd

**Comment by gsauthof** [comment]
PS: The printed restart command isn't the correct one:

    systemctl restart polkitd             # printed
    systemctl restart polkit.service  # works

Note the missing `d` at the end of the service name.

Seems to be fixable with a rename configuration in `applications.xml`.
