### ISSUE TITLE
Oracle Linux 7 support

### ISSUE THREAD

**Issue by lowey71** [FrostyX/tracer#87]
tracer.resources.exceptions.UnsupportedDistribution: You are running unsupported linux distribution

Please visit https://github.com/FrostyX/tracer/issues
and create new issue called 'Unknown or unsupported linux distribution: ol (v0.6.12)' if there isn't such.

**Comment by sean797** [comment]
Thanks @lowey71 This has already been fixed as part of https://github.com/FrostyX/tracer/issues/73. 
It will be support in the next release.
