### ISSUE TITLE
Unknown or unsupported linux distribution: korora (v0.6.12)

### ISSUE THREAD

**Issue by dominicusin** [FrostyX/tracer#90]
Tracer:
 Call to Tracer API ended unexpectedly:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 67, in transaction
    tracer = TracerFacade(packages)
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 80, in __init__
    self.apps = self.get_apps(packages)
  File "/usr/lib/python3.6/site-packages/dnf-plugins/tracer.py", line 84, in get_apps
    query = Query()
  File "/usr/lib/python3.6/site-packages/tracer/query.py", line 44, in __init__
    self._tracer = tracer(System.package_manager(), Rules, Applications, dump_memory)
  File "/usr/lib/python3.6/site-packages/tracer/resources/tracer.py", line 65, in __init__
    raise UnsupportedDistribution(System.distribution())
tracer.resources.exceptions.UnsupportedDistribution: You are running unsupported linux distribution

Please visit https://github.com/FrostyX/tracer/issues
and create new issue called 'Unknown or unsupported linux distribution: korora (v0.6.12)' if there isn't such.

Don't you have an GitHub account? Please report this issue on frostyx@email.cz

Please visit https://github.com/FrostyX/tracer/issues and submit the issue. Thank you
We apologize for any inconvenience

**Comment by sean797** [comment]
I believe this will work in 0.6.13, which includes https://github.com/FrostyX/tracer/commit/bb952e073014be789a24e8b88b05b8e332e8253b among other things.

Basically if `/etc/os-release` includes `["gentoo", "debian", "rhel", "centos", "ol", "mageia", "arch", "archarm", "fedora"]` in the `ID_LIKE` field. 

Does `ID_LIKE` in your `/etc/os-release` include one of these?

**Comment by dominicusin** [comment]
cat /etc/os-release

NAME=Korora
VERSION="25 (Gurgle)"
ID=korora
ID_LIKE=fedora
VERSION_ID=25
PRETTY_NAME="Korora 25 (Gurgle)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:kororaproject:korora:25"
HOME_URL="https://kororaproject.org/"
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
