### ISSUE TITLE
Kernel detection Problem

### ISSUE THREAD

**Issue by gabrielstein** [FrostyX/tracer#92]
Hello!

I'm using foreman+katello and all Servers are CentOS 7. The latest version from tracer has a feature related to kernel detection that doesn't works correctly. It says on foreman to reboot the server, made it ten times and doesn't works.

The buggy Function is hier: https://github.com/FrostyX/tracer/blob/master/tracer/resources/tracer.py#L132-L136

* Running in on python "prompt"

`
 import os
 next(os.walk('/lib/modules/'))[1]
['3.10.0-514.el7.x86_64', '3.10.0-514.26.2.el7.x86_64']
 os.uname()[2]
'3.10.0-514.26.2.el7.x86_64'
` 

This compare the versions using the content from /lib/modules, but it is everything ok!

* ls /lib/modules

`
drwxr-xr-x.  4 root root   69  6. Jul 15:44 .
dr-xr-xr-x. 29 root root 4,0K  8. Sep 16:48 ..
drwxr-xr-x.  7 root root 4,0K  6. Jul 15:44 3.10.0-514.26.2.el7.x86_64
drwxr-xr-x.  7 root root 4,0K  6. Jul 15:39 3.10.0-514.el7.x86_64
`

* uname -a

`
Linux <SERVER> 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
` 

# On Servers running an old version from tracer it works!

* rpm -qa | grep tracer
tracer-common-0.6.13-2.el7.noarch
python2-tracer-0.6.13-2.el7.noarch

# But on latest, doesn't works!

* rpm -qa | grep tracer
python2-tracer-0.6.12-4.el7.noarch
tracer-common-0.6.12-4.el7.noarch

TIA!

**Comment by sean797** [comment]
Thanks @gabrielstein It looks like were probably should use `parse_version` instead


```
>>> from pkg_resources import parse_version
>>> from distutils.version import LooseVersion
>>> 
>>> 
>>> un = '3.10.0-514.26.2.el7.x86_64'
>>> LooseVersion(un) < LooseVersion('3.10.0-514.el7.x86_64')
True
>>> parse_version(un) < parse_version('3.10.0-514.el7.x86_64')
False
>>> LooseVersion(un) < LooseVersion('3.10.0-514.26.2.el7.x86_64')
False
>>> parse_version(un) < parse_version('3.10.0-514.26.2.el7.x86_64')
False

**Comment by gabrielstein** [comment]
Thank you @sean797 
Cool, you will provide a patch? I downgraded the packages now and it works, without kernel detection.
